import ArticleList from "@/components/Article/List";
import NavBar from "@/components/NavBar";
import { Box } from "@mui/material";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>News Aggregator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <NavBar />
        <Box>
          <ArticleList />
        </Box>
      </main>
    </>
  );
}
